### ISSUE TITLE
filter reintialize button

### ISSUE THREAD

**Issue by guillaumemoby** [disc-in/UltimateApp#242]
When We re initialise on the filter page. The user wants to stay on the filter page 
![filter2](https://user-images.githubusercontent.com/56125567/98849234-30877000-2453-11eb-8ac8-b3715fcf6ce4.jpg)
Adding a big green validation button at the bottom of the page as on the session page

**Comment by sallesma** [comment]
Idea:
- Display "See the X drills" as the button text instead of the "X drills available" at the top
