### ISSUE TITLE
Changing the editor play bar

### ISSUE THREAD

**Issue by guillaumemoby** [disc-in/UltimateApp#243]
The user can get confuse with the play button. It's making as an arrow and the timeline is too big.
![play dril](https://user-images.githubusercontent.com/56125567/98848832-945d6900-2452-11eb-8845-3a195e66a399.jpg)

**Comment by sallesma** [comment]
We also need to fix this issue at the same time:

> Problem with a button + and -
> the play button is not obvious enough
> ![editor](https://user-images.githubusercontent.com/56125567/98846767-ba353e80-244f-11eb-99a1-173b6215e1d3.jpg)
